(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(org-agenda-files
   '("/Users/dbaggero/doc/content/agenda/tasks.org" "/Users/dbaggero/doc/content/agenda/events.org" "/Users/dbaggero/doc/content/work/tasks.org" "/Users/dbaggero/doc/content/journal/2022/08/18.org"))
 '(package-selected-packages
   '(emms beacon hl-todo highlight-indent-guides highlight-symbol rainbow-delimiters rainbow-mode visual-fill-column major-mode-hydra neotree pdf-tools embark orderless marginalia consult-ghq affe consult-flycheck consult vertico-posframe vertico projectile anzu doom-themes exec-path-from-shell mode-icons smart-mode-line all-the-icons git-gutter magit git-modes docker-tramp docker which-key company yasnippet flyspell-correct flyspell flycheck ace-window undo-fu package-utils hydra el-get leaf-keywords)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(aw-leading-char-face ((t (:height 4.0 :foreground "#f1fa8c"))) nil "Customized with leaf in `ace-window' block at `/Users/dbaggero/.emacs.d/config.el'")
 '(company-template-field ((t (:foreground "#ff79c6"))) nil "Customized with leaf in `company' block at `/Users/dbaggero/.emacs.d/config.el'")
 '(company-tooltip ((t (:background "#323445"))) nil "Customized with leaf in `company' block at `/Users/dbaggero/.emacs.d/config.el'")
 '(flyspell-duplicate ((t (:underline (:color "#50fa7b" :style wave)))) nil "Customized with leaf in `flyspell' block at `/Users/dbaggero/.emacs.d/config.el'")
 '(flyspell-incorrect ((t (:underline (:color "#f1fa8c" :style wave)))) nil "Customized with leaf in `flyspell' block at `/Users/dbaggero/.emacs.d/config.el'")
 '(font-lock-variable-name-face ((t (:foreground "violet"))) nil "Customized with leaf in `yaml-mode' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(git-gutter:added ((t (:foreground "#50fa7b"))) nil "Customized with leaf in `git-gutter' block at `/Users/dbaggero/.emacs.d/config.el'")
 '(git-gutter:deleted ((t (:foreground "#ff79c6"))) nil "Customized with leaf in `git-gutter' block at `/Users/dbaggero/.emacs.d/config.el'")
 '(git-gutter:modified ((t (:foreground "#f1fa8c"))) nil "Customized with leaf in `git-gutter' block at `/Users/dbaggero/.emacs.d/config.el'")
 '(hl-line ((t (:background "#3B4252" :extend t))) nil "Customized with leaf in `nano-modeline' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(hydra-face-amaranth ((t (:foreground "#f1fa8c"))) nil "Customized with leaf in `*hydra-theme' block at `/Users/dbaggero/.emacs.d/config.el'")
 '(hydra-face-blue ((t (:foreground "#8be9fd"))) nil "Customized with leaf in `*hydra-theme' block at `/Users/dbaggero/.emacs.d/config.el'")
 '(hydra-face-pink ((t (:foreground "#ff79c6"))) nil "Customized with leaf in `*hydra-theme' block at `/Users/dbaggero/.emacs.d/config.el'")
 '(hydra-face-red ((t (:foreground "#bd93f9"))) nil "Customized with leaf in `*hydra-theme' block at `/Users/dbaggero/.emacs.d/config.el'")
 '(hydra-face-teal ((t (:foreground "#61bfff"))) nil "Customized with leaf in `*hydra-theme' block at `/Users/dbaggero/.emacs.d/config.el'")
 '(hydra-posframe-border-face ((t (:background "#323445"))) nil "Customized with leaf in `hydra-posframe' block at `/Users/dbaggero/.emacs.d/config.el'")
 '(imenu-list-entry-face-1 ((t (:foreground "white"))) nil "Customized with leaf in `imenu-list' block at `/Users/dbaggero/.emacs.d/config.el'")
 '(imenu-list-entry-subalist-face-0 ((nil (:weight normal))) nil "Customized with leaf in `imenu-list' block at `/Users/dbaggero/.emacs.d/config.el'")
 '(imenu-list-entry-subalist-face-1 ((nil (:weight normal))) nil "Customized with leaf in `imenu-list' block at `/Users/dbaggero/.emacs.d/config.el'")
 '(imenu-list-entry-subalist-face-2 ((nil (:weight normal))) nil "Customized with leaf in `imenu-list' block at `/Users/dbaggero/.emacs.d/config.el'")
 '(imenu-list-entry-subalist-face-3 ((nil (:weight normal))) nil "Customized with leaf in `imenu-list' block at `/Users/dbaggero/.emacs.d/config.el'")
 '(lsp-ui-doc-background ((t (:background "#282a36"))) nil "Customized with leaf in `lsp-ui' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(lsp-ui-doc-header ((t (:foreground "#76e0f3" :weight bold))) nil "Customized with leaf in `lsp-ui' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(lsp-ui-doc-url ((t (:foreground "#6272a4"))) nil "Customized with leaf in `lsp-ui' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(marginalia-documentation ((t (:foreground "#6272a4"))) nil "Customized with leaf in `marginalia' block at `/Users/dbaggero/.emacs.d/config.el'")
 '(markdown-bold-face ((t (:foreground "#f8f8f2" :weight bold))) nil "Customized with leaf in `markdown-mode' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(markdown-gfm-checkbox-face ((t (:foreground "#6272a4"))) nil "Customized with leaf in `markdown-mode' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(markdown-header-delimiter-face ((t (:foreground "#6272a4" :weight normal))) nil "Customized with leaf in `markdown-mode' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(markdown-header-face-1 ((t (:inherit outline-1 :weight bold :height 1.5))) nil "Customized with leaf in `markdown-mode' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(markdown-header-face-2 ((t (:inherit outline-1 :weight normal :height 1.2))) nil "Customized with leaf in `markdown-mode' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(markdown-header-face-3 ((t (:inherit outline-1 :weight normal :height 1.1))) nil "Customized with leaf in `markdown-mode' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(markdown-header-face-4 ((t (:inherit outline-1 :weight normal))) nil "Customized with leaf in `markdown-mode' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(markdown-italic-face ((t (:foreground "#f8f8f2" :slant italic))) nil "Customized with leaf in `markdown-mode' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(markdown-link-face ((t (:foreground "#f1fa8c"))) nil "Customized with leaf in `markdown-mode' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(markdown-list-face ((t (:foreground "#6272a4"))) nil "Customized with leaf in `markdown-mode' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(markdown-metadata-key-face ((t (:foreground "#6272a4"))) nil "Customized with leaf in `markdown-mode' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(markdown-metadata-value-face ((t (:foreground "#8995ba"))) nil "Customized with leaf in `markdown-mode' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(markdown-pre-face ((t (:foreground "#8be9fd"))) nil "Customized with leaf in `markdown-mode' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(markdown-url-face ((t (:foreground "#6272a4"))) nil "Customized with leaf in `markdown-mode' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(mode-line ((t (:background "#282a36"))) nil "Customized with leaf in `nano-modeline' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(mode-line-inactive ((t (:background "#282a36"))) nil "Customized with leaf in `nano-modeline' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(mozc-cand-overlay-even-face ((t (:background "#323445" :foreground "#8995ba"))) nil "Customized with leaf in `mozc-posframe' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(mozc-cand-overlay-focused-face ((t (:background "#44475a" :foreground "#76e0f3"))) nil "Customized with leaf in `mozc-posframe' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(mozc-cand-overlay-footer-face ((t (:foreground "#6272a4"))) nil "Customized with leaf in `mozc-posframe' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(mozc-cand-overlay-odd-face ((t (:background "#323445" :foreground "#8995ba"))) nil "Customized with leaf in `mozc-posframe' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(mozc-cand-posframe-border-face ((t (:background "#323445"))) nil "Customized with leaf in `mozc-posframe' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(nano-face-header-critical ((t (:foreground "#282a36" :background "#bd93f9"))) t "Customized with leaf in `nano-modeline' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(nano-face-header-default ((t (:foreground "#b0b8d1" :background "#44475a"))) t "Customized with leaf in `nano-modeline' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(nano-face-header-faded ((t (:foreground "#282a36" :background "#6272a4"))) t "Customized with leaf in `nano-modeline' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(nano-face-header-popout ((t (:foreground "#282a36" :background "#f1fa8c"))) t "Customized with leaf in `nano-modeline' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(nano-face-header-salient ((t (:foreground "#282a36" :background "#0189cc"))) t "Customized with leaf in `nano-modeline' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(nano-face-header-strong ((t (:foreground "#f8f8f2" :background "#44475a" :weight bold))) t "Customized with leaf in `nano-modeline' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(nano-face-subtle ((t (:foreground "#282a36" :background "#44475a"))) t "Customized with leaf in `nano-modeline' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(org-checkbox ((t (:foreground "#bd93f9"))) nil "Customized with leaf in `org-theme' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(org-date ((t (:foreground "#8995ba"))) nil "Customized with leaf in `org-theme' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(org-document-title ((t (:foreground "#f8f8f2"))) nil "Customized with leaf in `org-theme' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(org-done ((t (:background "#373844" :foreground "#216933" :strike-through nil :weight bold :width condensed))) nil "Customized with leaf in `org-theme' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(org-drawer ((t (:foreground "#44475a"))) nil "Customized with leaf in `org-theme' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(org-footnote ((t (:foreground "#76e0f3"))) nil "Customized with leaf in `org-theme' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(org-journal-calendar-entry-face ((t (:foreground "#ff79c6"))) nil "Customized with leaf in `org-journal' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(org-level-1 ((t (:inherit outline-1 :height 1.2))) nil "Customized with leaf in `org-theme' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(org-level-2 ((t (:inherit outline-2 :weight normal))) nil "Customized with leaf in `org-theme' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(org-level-3 ((t (:inherit outline-3 :weight normal))) nil "Customized with leaf in `org-theme' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(org-level-4 ((t (:inherit outline-4 :weight normal))) nil "Customized with leaf in `org-theme' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(org-level-5 ((t (:inherit outline-5 :weight normal))) nil "Customized with leaf in `org-theme' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(org-level-6 ((t (:inherit outline-6 :weight normal))) nil "Customized with leaf in `org-theme' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(org-link ((t (:foreground "#f1fa8c" :underline nil :weight normal))) nil "Customized with leaf in `org-theme' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(org-list-dt ((t (:foreground "#bd93f9"))) nil "Customized with leaf in `org-theme' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(org-meta-line ((t (:foreground "#6272a4"))) nil "Customized with leaf in `org-theme' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(org-modern-date-active ((t (:background "#373844" :foreground "#f8f8f2" :height 0.75 :weight light :width condensed))) nil "Customized with leaf in `org-modern' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(org-modern-date-inactive ((t (:background "#373844" :foreground "#b0b8d1" :height 0.75 :weight light :width condensed))) nil "Customized with leaf in `org-modern' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(org-modern-statistics ((t (:foreground "#6272a4" :weight light :width condensed))) nil "Customized with leaf in `org-modern' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(org-modern-tag ((t (:background "#44475a" :foreground "#b0b8d1" :height 0.75 :weight light :width condensed))) nil "Customized with leaf in `org-modern' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(org-modern-time-active ((t (:background "#44475a" :foreground "#f8f8f2" :height 0.75 :weight light :width condensed))) nil "Customized with leaf in `org-modern' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(org-modern-time-inactive ((t (:background "#44475a" :foreground "#b0b8d1" :height 0.75 :weight light :width condensed))) nil "Customized with leaf in `org-modern' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(org-priority ((t (:foreground "#ebe087"))) nil "Customized with leaf in `org-theme' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(org-scheduled-today ((t (:foreground "#f8f8f2"))) nil "Customized with leaf in `*org-agenda' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(org-special-keyword ((t (:foreground "#6272a4"))) nil "Customized with leaf in `org-theme' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(org-tag ((t (:foreground "#6272a4"))) nil "Customized with leaf in `org-theme' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(org-todo ((t (:foreground "#51fa7b" :weight bold :width condensed))) nil "Customized with leaf in `org-theme' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(show-paren-match ((nil (:background "#44475a" :foreground "#f1fa8c"))) nil "Customized with leaf in `*paren' block at `/Users/dbaggero/.emacs.d/config.el'")
 '(vertical-border ((t (:background "#282a36" :foreground "#1E2029"))) nil "Customized with leaf in `nano-modeline' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(vertico-posframe-border ((t (:background "#323445"))) nil "Customized with leaf in `vertico-posframe' block at `/Users/dbaggero/.emacs.d/init.el'")
 '(vertico-postframe-border ((t (:background "#323445"))) nil "Customized with leaf in `vertico-posframe' block at `/Users/dbaggero/.emacs.d/config.el'")
 '(vhl/default-face ((nil (:foreground "#FF3333" :background "#FFCDCD"))) nil "Customized with leaf in `volatile-highlights' block at `/Users/dbaggero/.emacs.d/config.el'")
 '(yas-field-highlight-face ((t (:foreground "#ff79c6"))) nil "Customized with leaf in `company' block at `/Users/dbaggero/.emacs.d/config.el'"))
